services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: studysanctuary
    ports:
      - "5450:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data